FROM ubuntu:trusty

RUN sudo apt-get update
RUN sudo apt-get install -q -y build-essential perl make \
        libssl-dev libpcre3-dev libncurses5-dev libreadline-dev

RUN sudo apt-get install -q -y libpam-dev

