#!/bin/bash

export RESTY_BUILDER_PARAM__PREFIX="/usr/local/resty"
export RESTY_BUILDER_PARAM__USER="resty"
export RESTY_BUILDER_PARAM__GROUP="resty"

export RESTY_BUILDER_PARAM__PACKAGE_VERSION="1.11.2.2"
export RESTY_BUILDER_PARAM__PACKAGE_NAME="resty"

export RESTY_BUILDER_PARAM__PACKAGE_ARCH=`uname -m`
export RESTY_BUILDER_PARAM__PACKAGE_ITERATION=""
export RESTY_BUILDER_PARAM__PACKAGE_TYPE=""
export RESTY_BUILDER_PARAM__PACKAGE_DESCRIPTION="A custom openresty build."
export RESTY_BUILDER_PARAM__PACKAGE_MAINTAINER_EMAIL="maintainer@example.com"

export RESTY_BUILDER_DEB_NAME_BASE="${RESTY_BUILDER_PARAM__PACKAGE_NAME}-${RESTY_BUILDER_PARAM__PACKAGE_VERSION}"
